language: java

jdk:
  - oraclejdk8

before_install:
  # update to java 8
  - sudo git clone https://github.com/NLPchina/nlp-lang.git
  - sudo cd ./nlp-lang
  - sudo mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true

script: 
  - mvn test
